
// Generated by Cadence Genus(TM) Synthesis Solution 22.17-s071_1
// Generated on: Aug  3 2026 20:57:04 KST (Aug  3 2026 11:57:04 UTC)

// Verification Directory fv/watch 

module watch(clk, rst_n, sec_bcd1, sec_bcd10, min_bcd1, min_bcd10,
     hour_bcd1, hour_bcd10);
  input clk, rst_n;
  output [3:0] sec_bcd1, sec_bcd10, min_bcd1, min_bcd10, hour_bcd1,
       hour_bcd10;
  wire clk, rst_n;
  wire [3:0] sec_bcd1, sec_bcd10, min_bcd1, min_bcd10, hour_bcd1,
       hour_bcd10;
  wire n_0, n_1, n_2, n_3, n_4, n_5, n_6, n_7;
  wire n_8, n_9, n_10, n_11, n_12, n_13, n_14, n_15;
  wire n_16, n_17, n_18, n_20, n_21, n_22, n_23, n_24;
  wire n_25, n_27, n_28, n_29, n_30, n_31, n_32, n_33;
  wire n_34, n_35, n_36, n_37, n_38, n_39, n_41, n_42;
  wire n_43, n_45, n_46, n_47, n_48, n_49, n_50, n_51;
  wire n_52, n_53, n_54, n_55, n_56, n_57, n_58, n_59;
  wire n_60, n_61, n_62, n_63, n_64, n_65, n_66, n_67;
  wire n_68, n_69, n_70, n_71, n_72, n_75, n_76, r_hour_tick;
  wire r_min_tick;
  DFFRHQX1 \hour_bcd10_reg[3] (.RN (rst_n), .CK (clk), .D (n_72), .Q
       (hour_bcd10[3]));
  DFFRHQX1 \hour_bcd10_reg[2] (.RN (rst_n), .CK (clk), .D (n_71), .Q
       (hour_bcd10[2]));
  XNOR2X1 g2491__2398(.A (hour_bcd10[3]), .B (n_70), .Y (n_72));
  OA21X1 g2494__5107(.A0 (hour_bcd10[2]), .A1 (n_67), .B0 (n_70), .Y
       (n_71));
  DFFRHQX1 \hour_bcd10_reg[1] (.RN (rst_n), .CK (clk), .D (n_68), .Q
       (hour_bcd10[1]));
  DFFRHQX1 \hour_bcd1_reg[3] (.RN (rst_n), .CK (clk), .D (n_69), .Q
       (hour_bcd1[3]));
  AO22XL g2498__6260(.A0 (hour_bcd1[2]), .A1 (n_62), .B0
       (hour_bcd1[3]), .B1 (n_56), .Y (n_69));
  OAI31X1 g2499__4319(.A0 (hour_bcd10[1]), .A1 (n_66), .A2 (n_65), .B0
       (n_64), .Y (n_68));
  NAND2X1 g2500__8428(.A (hour_bcd10[2]), .B (n_67), .Y (n_70));
  SDFFRHQX1 \hour_bcd10_reg[0] (.RN (rst_n), .CK (clk), .D (n_66), .SI
       (hour_bcd10[0]), .SE (n_65), .Q (hour_bcd10[0]));
  NOR3BX1 g2503__5526(.AN (hour_bcd10[1]), .B (n_66), .C (n_65), .Y
       (n_67));
  NAND2X1 g2504__6783(.A (hour_bcd10[1]), .B (n_59), .Y (n_64));
  OAI2BB1X1 g2502__3680(.A0N (hour_bcd1[2]), .A1N (n_61), .B0 (n_60),
       .Y (n_63));
  OAI21XL g2505__1617(.A0 (hour_bcd1[3]), .A1 (n_61), .B0 (n_57), .Y
       (n_62));
  SDFFRHQX1 \hour_bcd1_reg[1] (.RN (rst_n), .CK (clk), .D (n_54), .SI
       (n_53), .SE (hour_bcd1[1]), .Q (hour_bcd1[1]));
  OAI211X1 g2506__2802(.A0 (hour_bcd10[0]), .A1 (n_11), .B0
       (hour_bcd1[1]), .C0 (n_58), .Y (n_60));
  OAI211X1 g2508__1705(.A0 (hour_bcd10[0]), .A1 (n_13), .B0 (n_58), .C0
       (n_14), .Y (n_59));
  NAND2BX1 g2507__5122(.AN (n_57), .B (n_58), .Y (n_65));
  DFFRHQX1 \hour_bcd1_reg[0] (.RN (rst_n), .CK (clk), .D (n_52), .Q
       (hour_bcd1[0]));
  OAI21X1 g2511__8246(.A0 (hour_bcd1[2]), .A1 (n_12), .B0 (n_55), .Y
       (n_56));
  NAND2X1 g2513__7098(.A (hour_bcd1[1]), .B (n_55), .Y (n_61));
  AOI21X1 g2512__6131(.A0 (hour_bcd1[3]), .A1 (n_1), .B0 (n_53), .Y
       (n_54));
  NOR2X1 g2510__1881(.A (hour_bcd1[2]), .B (n_53), .Y (n_58));
  OA21X1 g2517__5115(.A0 (r_hour_tick), .A1 (hour_bcd1[0]), .B0 (n_53),
       .Y (n_52));
  DFFRHQX1 \min_bcd10_reg[3] (.RN (rst_n), .CK (clk), .D (n_51), .Q
       (min_bcd10[3]));
  INVX1 g2514(.A (n_53), .Y (n_55));
  SDFFRHQX1 \min_bcd10_reg[2] (.RN (rst_n), .CK (clk), .D (n_50), .SI
       (n_75), .SE (min_bcd10[2]), .Q (min_bcd10[2]));
  NAND2X1 g2521__7482(.A (r_hour_tick), .B (hour_bcd1[0]), .Y (n_53));
  OAI2BB1X1 g2518__4733(.A0N (n_46), .A1N (n_50), .B0 (n_49), .Y
       (n_51));
  DFFRHQX1 \min_bcd1_reg[3] (.RN (rst_n), .CK (clk), .D (n_48), .Q
       (min_bcd1[3]));
  OAI2BB1X1 g2520__6161(.A0N (min_bcd10[2]), .A1N (n_50), .B0
       (min_bcd10[3]), .Y (n_49));
  OAI2BB1X1 g2529__9315(.A0N (min_bcd1[3]), .A1N (n_34), .B0 (n_43), .Y
       (n_48));
  DFFRHQX1 r_hour_tick_reg(.RN (rst_n), .CK (clk), .D (n_47), .Q
       (r_hour_tick));
  DFFRHQX1 \min_bcd10_reg[0] (.RN (rst_n), .CK (clk), .D (n_41), .Q
       (min_bcd10[0]));
  SDFFRHQX1 \min_bcd10_reg[1] (.RN (rst_n), .CK (clk), .D (n_3), .SI
       (min_bcd10[1]), .SE (n_45), .Q (min_bcd10[1]));
  NOR3BX1 g2525__9945(.AN (n_46), .B (min_bcd10[1]), .C (n_45), .Y
       (n_47));
  AOI22X1 g2533__2346(.A0 (min_bcd1[2]), .A1 (n_38), .B0 (min_bcd1[1]),
       .B1 (n_35), .Y (n_43));
  NOR2X1 g2527__1666(.A (n_42), .B (n_45), .Y (n_50));
  OA21X1 g2532__7410(.A0 (min_bcd10[0]), .A1 (n_39), .B0 (n_45), .Y
       (n_41));
  SDFFRHQX1 \min_bcd1_reg[2] (.RN (rst_n), .CK (clk), .D (n_33), .SI
       (min_bcd1[2]), .SE (n_37), .Q (min_bcd1[2]));
  NAND2X1 g2534__6417(.A (min_bcd10[0]), .B (n_39), .Y (n_45));
  NOR2X1 g2536__5477(.A (min_bcd1[3]), .B (n_37), .Y (n_38));
  OAI32X1 g2535__2398(.A0 (min_bcd1[1]), .A1 (n_35), .A2 (n_31), .B0
       (n_0), .B1 (n_32), .Y (n_36));
  DFFRHQX1 \min_bcd1_reg[0] (.RN (rst_n), .CK (clk), .D (n_30), .Q
       (min_bcd1[0]));
  OAI21X1 g2539__5107(.A0 (min_bcd1[1]), .A1 (n_33), .B0 (n_32), .Y
       (n_34));
  NOR3BX1 g2537__6260(.AN (n_35), .B (min_bcd1[1]), .C (n_31), .Y
       (n_39));
  NAND2X1 g2540__4319(.A (min_bcd1[1]), .B (n_32), .Y (n_37));
  DFFRHQX1 \sec_bcd10_reg[3] (.RN (rst_n), .CK (clk), .D (n_29), .Q
       (sec_bcd10[3]));
  OA21X1 g2544__8428(.A0 (r_min_tick), .A1 (min_bcd1[0]), .B0 (n_31),
       .Y (n_30));
  INVX1 g2541(.A (n_31), .Y (n_32));
  SDFFRHQX1 \sec_bcd10_reg[2] (.RN (rst_n), .CK (clk), .D (n_28), .SI
       (n_76), .SE (sec_bcd10[2]), .Q (sec_bcd10[2]));
  OAI2BB1X1 g2545__5526(.A0N (n_24), .A1N (n_28), .B0 (n_27), .Y
       (n_29));
  NAND2X1 g2548__6783(.A (r_min_tick), .B (min_bcd1[0]), .Y (n_31));
  OAI2BB1X1 g2547__3680(.A0N (sec_bcd10[2]), .A1N (n_28), .B0
       (sec_bcd10[3]), .Y (n_27));
  DFFRHQX1 r_min_tick_reg(.RN (rst_n), .CK (clk), .D (n_25), .Q
       (r_min_tick));
  DFFRHQX1 \sec_bcd10_reg[0] (.RN (rst_n), .CK (clk), .D (n_22), .Q
       (sec_bcd10[0]));
  DFFRHQX1 \sec_bcd1_reg[3] (.RN (rst_n), .CK (clk), .D (n_21), .Q
       (sec_bcd1[3]));
  SDFFRHQX1 \sec_bcd10_reg[1] (.RN (rst_n), .CK (clk), .D (n_4), .SI
       (sec_bcd10[1]), .SE (n_23), .Q (sec_bcd10[1]));
  NOR3BX1 g2552__2802(.AN (n_24), .B (sec_bcd10[1]), .C (n_23), .Y
       (n_25));
  OA21X1 g2557__1705(.A0 (sec_bcd10[0]), .A1 (n_18), .B0 (n_23), .Y
       (n_22));
  OAI2BB1X1 g2558__5122(.A0N (sec_bcd1[3]), .A1N (n_8), .B0 (n_17), .Y
       (n_21));
  NOR2X1 g2551__8246(.A (n_20), .B (n_23), .Y (n_28));
  NAND2X1 g2560__7098(.A (sec_bcd10[0]), .B (n_18), .Y (n_23));
  AOI22X1 g2561__6131(.A0 (sec_bcd1[2]), .A1 (n_6), .B0 (sec_bcd1[1]),
       .B1 (n_15), .Y (n_17));
  OAI32X1 g2562__1881(.A0 (sec_bcd1[1]), .A1 (n_2), .A2 (n_15), .B0
       (sec_bcd1[0]), .B1 (n_9), .Y (n_16));
  SDFFRHQX1 \sec_bcd1_reg[2] (.RN (rst_n), .CK (clk), .D (n_7), .SI
       (sec_bcd1[2]), .SE (n_5), .Q (sec_bcd1[2]));
  NAND2X1 g2569__5115(.A (hour_bcd10[0]), .B (n_57), .Y (n_14));
  NOR2BX1 g2563__7482(.AN (n_10), .B (n_12), .Y (n_13));
  NAND2X1 g2564__4733(.A (hour_bcd10[1]), .B (n_10), .Y (n_11));
  AND3XL g2565__6161(.A (sec_bcd1[0]), .B (n_9), .C (n_15), .Y (n_18));
  OAI21XL g2570__9315(.A0 (sec_bcd1[1]), .A1 (n_7), .B0 (sec_bcd1[0]),
       .Y (n_8));
  NOR2X1 g2566__9945(.A (sec_bcd1[3]), .B (n_5), .Y (n_6));
  NOR2X1 g2567__2883(.A (sec_bcd10[1]), .B (n_24), .Y (n_4));
  NOR2X1 g2568__2346(.A (min_bcd10[1]), .B (n_46), .Y (n_3));
  NOR3X1 g2571__1666(.A (hour_bcd10[3]), .B (hour_bcd1[3]), .C
       (hour_bcd10[2]), .Y (n_10));
  NAND2X1 g2578__7410(.A (hour_bcd1[3]), .B (n_12), .Y (n_57));
  NAND2X1 g2573__6417(.A (sec_bcd1[1]), .B (sec_bcd1[0]), .Y (n_5));
  NOR2BX1 g2575__5477(.AN (min_bcd10[2]), .B (min_bcd10[3]), .Y (n_46));
  NOR2BX1 g2576__2398(.AN (min_bcd1[3]), .B (min_bcd1[2]), .Y (n_35));
  NOR2BX1 g2577__5107(.AN (sec_bcd10[2]), .B (sec_bcd10[3]), .Y (n_24));
  NOR2BX1 g2572__6260(.AN (sec_bcd1[3]), .B (sec_bcd1[2]), .Y (n_15));
  INVX1 g2584(.A (min_bcd1[2]), .Y (n_33));
  INVX1 g2582(.A (sec_bcd10[1]), .Y (n_20));
  INVX1 g2587(.A (hour_bcd1[1]), .Y (n_12));
  INVX1 g2583(.A (min_bcd10[1]), .Y (n_42));
  INVX1 g2580(.A (sec_bcd1[2]), .Y (n_7));
  INVX1 g2588(.A (hour_bcd10[0]), .Y (n_66));
  DFFRX1 \hour_bcd1_reg[2] (.RN (rst_n), .CK (clk), .D (n_63), .Q
       (hour_bcd1[2]), .QN (n_1));
  DFFRX1 \sec_bcd1_reg[0] (.RN (rst_n), .CK (clk), .D (n_2), .Q
       (sec_bcd1[0]), .QN (n_2));
  DFFRX1 \min_bcd1_reg[1] (.RN (rst_n), .CK (clk), .D (n_36), .Q
       (min_bcd1[1]), .QN (n_0));
  DFFRX1 \sec_bcd1_reg[1] (.RN (rst_n), .CK (clk), .D (n_16), .Q
       (sec_bcd1[1]), .QN (n_9));
  AO21XL g2(.A0 (min_bcd10[3]), .A1 (n_42), .B0 (n_45), .Y (n_75));
  AO21XL g2623(.A0 (sec_bcd10[3]), .A1 (n_20), .B0 (n_23), .Y (n_76));
endmodule

