
//input ports
add mapped point clk clk -type PI PI
add mapped point rst_n rst_n -type PI PI
add mapped point i_in1[31] i_in1[31] -type PI PI
add mapped point i_in1[30] i_in1[30] -type PI PI
add mapped point i_in1[29] i_in1[29] -type PI PI
add mapped point i_in1[28] i_in1[28] -type PI PI
add mapped point i_in1[27] i_in1[27] -type PI PI
add mapped point i_in1[26] i_in1[26] -type PI PI
add mapped point i_in1[25] i_in1[25] -type PI PI
add mapped point i_in1[24] i_in1[24] -type PI PI
add mapped point i_in1[23] i_in1[23] -type PI PI
add mapped point i_in1[22] i_in1[22] -type PI PI
add mapped point i_in1[21] i_in1[21] -type PI PI
add mapped point i_in1[20] i_in1[20] -type PI PI
add mapped point i_in1[19] i_in1[19] -type PI PI
add mapped point i_in1[18] i_in1[18] -type PI PI
add mapped point i_in1[17] i_in1[17] -type PI PI
add mapped point i_in1[16] i_in1[16] -type PI PI
add mapped point i_in1[15] i_in1[15] -type PI PI
add mapped point i_in1[14] i_in1[14] -type PI PI
add mapped point i_in1[13] i_in1[13] -type PI PI
add mapped point i_in1[12] i_in1[12] -type PI PI
add mapped point i_in1[11] i_in1[11] -type PI PI
add mapped point i_in1[10] i_in1[10] -type PI PI
add mapped point i_in1[9] i_in1[9] -type PI PI
add mapped point i_in1[8] i_in1[8] -type PI PI
add mapped point i_in1[7] i_in1[7] -type PI PI
add mapped point i_in1[6] i_in1[6] -type PI PI
add mapped point i_in1[5] i_in1[5] -type PI PI
add mapped point i_in1[4] i_in1[4] -type PI PI
add mapped point i_in1[3] i_in1[3] -type PI PI
add mapped point i_in1[2] i_in1[2] -type PI PI
add mapped point i_in1[1] i_in1[1] -type PI PI
add mapped point i_in1[0] i_in1[0] -type PI PI
add mapped point i_in2[31] i_in2[31] -type PI PI
add mapped point i_in2[30] i_in2[30] -type PI PI
add mapped point i_in2[29] i_in2[29] -type PI PI
add mapped point i_in2[28] i_in2[28] -type PI PI
add mapped point i_in2[27] i_in2[27] -type PI PI
add mapped point i_in2[26] i_in2[26] -type PI PI
add mapped point i_in2[25] i_in2[25] -type PI PI
add mapped point i_in2[24] i_in2[24] -type PI PI
add mapped point i_in2[23] i_in2[23] -type PI PI
add mapped point i_in2[22] i_in2[22] -type PI PI
add mapped point i_in2[21] i_in2[21] -type PI PI
add mapped point i_in2[20] i_in2[20] -type PI PI
add mapped point i_in2[19] i_in2[19] -type PI PI
add mapped point i_in2[18] i_in2[18] -type PI PI
add mapped point i_in2[17] i_in2[17] -type PI PI
add mapped point i_in2[16] i_in2[16] -type PI PI
add mapped point i_in2[15] i_in2[15] -type PI PI
add mapped point i_in2[14] i_in2[14] -type PI PI
add mapped point i_in2[13] i_in2[13] -type PI PI
add mapped point i_in2[12] i_in2[12] -type PI PI
add mapped point i_in2[11] i_in2[11] -type PI PI
add mapped point i_in2[10] i_in2[10] -type PI PI
add mapped point i_in2[9] i_in2[9] -type PI PI
add mapped point i_in2[8] i_in2[8] -type PI PI
add mapped point i_in2[7] i_in2[7] -type PI PI
add mapped point i_in2[6] i_in2[6] -type PI PI
add mapped point i_in2[5] i_in2[5] -type PI PI
add mapped point i_in2[4] i_in2[4] -type PI PI
add mapped point i_in2[3] i_in2[3] -type PI PI
add mapped point i_in2[2] i_in2[2] -type PI PI
add mapped point i_in2[1] i_in2[1] -type PI PI
add mapped point i_in2[0] i_in2[0] -type PI PI

//output ports
add mapped point o_out1[31] o_out1[31] -type PO PO
add mapped point o_out1[30] o_out1[30] -type PO PO
add mapped point o_out1[29] o_out1[29] -type PO PO
add mapped point o_out1[28] o_out1[28] -type PO PO
add mapped point o_out1[27] o_out1[27] -type PO PO
add mapped point o_out1[26] o_out1[26] -type PO PO
add mapped point o_out1[25] o_out1[25] -type PO PO
add mapped point o_out1[24] o_out1[24] -type PO PO
add mapped point o_out1[23] o_out1[23] -type PO PO
add mapped point o_out1[22] o_out1[22] -type PO PO
add mapped point o_out1[21] o_out1[21] -type PO PO
add mapped point o_out1[20] o_out1[20] -type PO PO
add mapped point o_out1[19] o_out1[19] -type PO PO
add mapped point o_out1[18] o_out1[18] -type PO PO
add mapped point o_out1[17] o_out1[17] -type PO PO
add mapped point o_out1[16] o_out1[16] -type PO PO
add mapped point o_out1[15] o_out1[15] -type PO PO
add mapped point o_out1[14] o_out1[14] -type PO PO
add mapped point o_out1[13] o_out1[13] -type PO PO
add mapped point o_out1[12] o_out1[12] -type PO PO
add mapped point o_out1[11] o_out1[11] -type PO PO
add mapped point o_out1[10] o_out1[10] -type PO PO
add mapped point o_out1[9] o_out1[9] -type PO PO
add mapped point o_out1[8] o_out1[8] -type PO PO
add mapped point o_out1[7] o_out1[7] -type PO PO
add mapped point o_out1[6] o_out1[6] -type PO PO
add mapped point o_out1[5] o_out1[5] -type PO PO
add mapped point o_out1[4] o_out1[4] -type PO PO
add mapped point o_out1[3] o_out1[3] -type PO PO
add mapped point o_out1[2] o_out1[2] -type PO PO
add mapped point o_out1[1] o_out1[1] -type PO PO
add mapped point o_out1[0] o_out1[0] -type PO PO
add mapped point o_out2[31] o_out2[31] -type PO PO
add mapped point o_out2[30] o_out2[30] -type PO PO
add mapped point o_out2[29] o_out2[29] -type PO PO
add mapped point o_out2[28] o_out2[28] -type PO PO
add mapped point o_out2[27] o_out2[27] -type PO PO
add mapped point o_out2[26] o_out2[26] -type PO PO
add mapped point o_out2[25] o_out2[25] -type PO PO
add mapped point o_out2[24] o_out2[24] -type PO PO
add mapped point o_out2[23] o_out2[23] -type PO PO
add mapped point o_out2[22] o_out2[22] -type PO PO
add mapped point o_out2[21] o_out2[21] -type PO PO
add mapped point o_out2[20] o_out2[20] -type PO PO
add mapped point o_out2[19] o_out2[19] -type PO PO
add mapped point o_out2[18] o_out2[18] -type PO PO
add mapped point o_out2[17] o_out2[17] -type PO PO
add mapped point o_out2[16] o_out2[16] -type PO PO
add mapped point o_out2[15] o_out2[15] -type PO PO
add mapped point o_out2[14] o_out2[14] -type PO PO
add mapped point o_out2[13] o_out2[13] -type PO PO
add mapped point o_out2[12] o_out2[12] -type PO PO
add mapped point o_out2[11] o_out2[11] -type PO PO
add mapped point o_out2[10] o_out2[10] -type PO PO
add mapped point o_out2[9] o_out2[9] -type PO PO
add mapped point o_out2[8] o_out2[8] -type PO PO
add mapped point o_out2[7] o_out2[7] -type PO PO
add mapped point o_out2[6] o_out2[6] -type PO PO
add mapped point o_out2[5] o_out2[5] -type PO PO
add mapped point o_out2[4] o_out2[4] -type PO PO
add mapped point o_out2[3] o_out2[3] -type PO PO
add mapped point o_out2[2] o_out2[2] -type PO PO
add mapped point o_out2[1] o_out2[1] -type PO PO
add mapped point o_out2[0] o_out2[0] -type PO PO

//inout ports




//Sequential Pins
add mapped point o_out2[28]/q o_out2_reg[28]/Q -type DFF DFF
add mapped point o_out1[30]/q o_out1_reg[30]/Q -type DFF DFF
add mapped point o_out1[28]/q o_out1_reg[28]/Q -type DFF DFF
add mapped point o_out1[24]/q o_out1_reg[24]/Q -type DFF DFF
add mapped point o_out1[16]/q o_out1_reg[16]/Q -type DFF DFF
add mapped point o_out2[3]/q o_out2_reg[3]/Q -type DFF DFF
add mapped point o_out1[0]/q o_out1_reg[0]/Q -type DFF DFF
add mapped point o_out2[0]/q o_out2_reg[0]/Q -type DFF DFF
add mapped point o_out2[31]/q o_out2_reg[31]/Q -type DFF DFF
add mapped point o_out2[5]/q o_out2_reg[5]/Q -type DFF DFF
add mapped point o_out1[15]/q o_out1_reg[15]/Q -type DFF DFF
add mapped point o_out2[30]/q o_out2_reg[30]/Q -type DFF DFF
add mapped point o_out2[29]/q o_out2_reg[29]/Q -type DFF DFF
add mapped point o_out2[8]/q o_out2_reg[8]/Q -type DFF DFF
add mapped point o_out1[23]/q o_out1_reg[23]/Q -type DFF DFF
add mapped point o_out1[14]/q o_out1_reg[14]/Q -type DFF DFF
add mapped point o_out2[26]/q o_out2_reg[26]/Q -type DFF DFF
add mapped point o_out2[27]/q o_out2_reg[27]/Q -type DFF DFF
add mapped point o_out1[13]/q o_out1_reg[13]/Q -type DFF DFF
add mapped point o_out1[31]/q o_out1_reg[31]/Q -type DFF DFF
add mapped point o_out2[25]/q o_out2_reg[25]/Q -type DFF DFF
add mapped point o_out2[12]/q o_out2_reg[12]/Q -type DFF DFF
add mapped point o_out1[27]/q o_out1_reg[27]/Q -type DFF DFF
add mapped point o_out1[22]/q o_out1_reg[22]/Q -type DFF DFF
add mapped point o_out1[12]/q o_out1_reg[12]/Q -type DFF DFF
add mapped point o_out2[14]/q o_out2_reg[14]/Q -type DFF DFF
add mapped point o_out2[24]/q o_out2_reg[24]/Q -type DFF DFF
add mapped point o_out2[23]/q o_out2_reg[23]/Q -type DFF DFF
add mapped point o_out1[11]/q o_out1_reg[11]/Q -type DFF DFF
add mapped point o_out1[8]/q o_out1_reg[8]/Q -type DFF DFF
add mapped point o_out2[22]/q o_out2_reg[22]/Q -type DFF DFF
add mapped point o_out2[21]/q o_out2_reg[21]/Q -type DFF DFF
add mapped point o_out2[11]/q o_out2_reg[11]/Q -type DFF DFF
add mapped point o_out1[10]/q o_out1_reg[10]/Q -type DFF DFF
add mapped point o_out2[20]/q o_out2_reg[20]/Q -type DFF DFF
add mapped point o_out2[19]/q o_out2_reg[19]/Q -type DFF DFF
add mapped point o_out1[9]/q o_out1_reg[9]/Q -type DFF DFF
add mapped point o_out2[18]/q o_out2_reg[18]/Q -type DFF DFF
add mapped point o_out2[9]/q o_out2_reg[9]/Q -type DFF DFF
add mapped point o_out1[29]/q o_out1_reg[29]/Q -type DFF DFF
add mapped point o_out1[26]/q o_out1_reg[26]/Q -type DFF DFF
add mapped point o_out1[20]/q o_out1_reg[20]/Q -type DFF DFF
add mapped point o_out2[16]/q o_out2_reg[16]/Q -type DFF DFF
add mapped point o_out2[15]/q o_out2_reg[15]/Q -type DFF DFF
add mapped point o_out1[7]/q o_out1_reg[7]/Q -type DFF DFF
add mapped point o_out2[13]/q o_out2_reg[13]/Q -type DFF DFF
add mapped point o_out1[19]/q o_out1_reg[19]/Q -type DFF DFF
add mapped point o_out1[6]/q o_out1_reg[6]/Q -type DFF DFF
add mapped point o_out1[21]/q o_out1_reg[21]/Q -type DFF DFF
add mapped point o_out1[5]/q o_out1_reg[5]/Q -type DFF DFF
add mapped point o_out2[10]/q o_out2_reg[10]/Q -type DFF DFF
add mapped point o_out2[17]/q o_out2_reg[17]/Q -type DFF DFF
add mapped point o_out1[25]/q o_out1_reg[25]/Q -type DFF DFF
add mapped point o_out1[18]/q o_out1_reg[18]/Q -type DFF DFF
add mapped point o_out1[4]/q o_out1_reg[4]/Q -type DFF DFF
add mapped point o_out2[7]/q o_out2_reg[7]/Q -type DFF DFF
add mapped point o_out1[3]/q o_out1_reg[3]/Q -type DFF DFF
add mapped point o_out2[6]/q o_out2_reg[6]/Q -type DFF DFF
add mapped point o_out1[17]/q o_out1_reg[17]/Q -type DFF DFF
add mapped point o_out1[2]/q o_out1_reg[2]/Q -type DFF DFF
add mapped point o_out2[4]/q o_out2_reg[4]/Q -type DFF DFF
add mapped point o_out1[1]/q o_out1_reg[1]/Q -type DFF DFF
add mapped point o_out2[2]/q o_out2_reg[2]/Q -type DFF DFF
add mapped point o_out2[1]/q o_out2_reg[1]/Q -type DFF DFF



//Black Boxes



//Empty Modules as Blackboxes
