
// Generated by Cadence Genus(TM) Synthesis Solution 22.17-s071_1
// Generated on: Jul  8 2026 06:28:05 KST (Jul  7 2026 21:28:05 UTC)

// Verification Directory fv/shift_register_sipo 

module shift_register_sipo(clk, rst_n, i_serial_in, load,
     o_parallel_out);
  input clk, rst_n, i_serial_in, load;
  output [7:0] o_parallel_out;
  wire clk, rst_n, i_serial_in, load;
  wire [7:0] o_parallel_out;
  wire [7:0] r_reg_data;
  SDFFRHQX1 \o_parallel_out_reg[4] (.RN (rst_n), .CK (clk), .D
       (o_parallel_out[4]), .SI (r_reg_data[4]), .SE (load), .Q
       (o_parallel_out[4]));
  SDFFRHQX1 \o_parallel_out_reg[1] (.RN (rst_n), .CK (clk), .D
       (o_parallel_out[1]), .SI (r_reg_data[1]), .SE (load), .Q
       (o_parallel_out[1]));
  SDFFRHQX1 \o_parallel_out_reg[3] (.RN (rst_n), .CK (clk), .D
       (o_parallel_out[3]), .SI (r_reg_data[3]), .SE (load), .Q
       (o_parallel_out[3]));
  SDFFRHQX1 \o_parallel_out_reg[0] (.RN (rst_n), .CK (clk), .D
       (o_parallel_out[0]), .SI (r_reg_data[0]), .SE (load), .Q
       (o_parallel_out[0]));
  SDFFRHQX1 \r_reg_data_reg[3] (.RN (rst_n), .CK (clk), .D
       (r_reg_data[2]), .SI (r_reg_data[3]), .SE (load), .Q
       (r_reg_data[3]));
  SDFFRHQX1 \r_reg_data_reg[2] (.RN (rst_n), .CK (clk), .D
       (r_reg_data[1]), .SI (r_reg_data[2]), .SE (load), .Q
       (r_reg_data[2]));
  SDFFRHQX1 \r_reg_data_reg[4] (.RN (rst_n), .CK (clk), .D
       (r_reg_data[3]), .SI (r_reg_data[4]), .SE (load), .Q
       (r_reg_data[4]));
  SDFFRHQX1 \r_reg_data_reg[5] (.RN (rst_n), .CK (clk), .D
       (r_reg_data[4]), .SI (r_reg_data[5]), .SE (load), .Q
       (r_reg_data[5]));
  SDFFRHQX1 \o_parallel_out_reg[5] (.RN (rst_n), .CK (clk), .D
       (o_parallel_out[5]), .SI (r_reg_data[5]), .SE (load), .Q
       (o_parallel_out[5]));
  SDFFRHQX1 \o_parallel_out_reg[7] (.RN (rst_n), .CK (clk), .D
       (o_parallel_out[7]), .SI (r_reg_data[7]), .SE (load), .Q
       (o_parallel_out[7]));
  SDFFRHQX1 \r_reg_data_reg[7] (.RN (rst_n), .CK (clk), .D
       (r_reg_data[6]), .SI (r_reg_data[7]), .SE (load), .Q
       (r_reg_data[7]));
  SDFFRHQX1 \o_parallel_out_reg[2] (.RN (rst_n), .CK (clk), .D
       (o_parallel_out[2]), .SI (r_reg_data[2]), .SE (load), .Q
       (o_parallel_out[2]));
  SDFFRHQX1 \o_parallel_out_reg[6] (.RN (rst_n), .CK (clk), .D
       (o_parallel_out[6]), .SI (r_reg_data[6]), .SE (load), .Q
       (o_parallel_out[6]));
  SDFFRHQX1 \r_reg_data_reg[1] (.RN (rst_n), .CK (clk), .D
       (r_reg_data[0]), .SI (r_reg_data[1]), .SE (load), .Q
       (r_reg_data[1]));
  SDFFRHQX1 \r_reg_data_reg[6] (.RN (rst_n), .CK (clk), .D
       (r_reg_data[5]), .SI (r_reg_data[6]), .SE (load), .Q
       (r_reg_data[6]));
  SDFFRHQX1 \r_reg_data_reg[0] (.RN (rst_n), .CK (clk), .D
       (i_serial_in), .SI (r_reg_data[0]), .SE (load), .Q
       (r_reg_data[0]));
endmodule

