
// Generated by Cadence Genus(TM) Synthesis Solution 22.17-s071_1
// Generated on: Jul  8 2026 06:25:23 KST (Jul  7 2026 21:25:23 UTC)

// Verification Directory fv/register 

module register(clk, rst_n, i_in1, i_in2, o_out1, o_out2);
  input clk, rst_n;
  input [31:0] i_in1, i_in2;
  output [31:0] o_out1, o_out2;
  wire clk, rst_n;
  wire [31:0] i_in1, i_in2;
  wire [31:0] o_out1, o_out2;
  DFFRHQX1 \o_out2_reg[28] (.RN (rst_n), .CK (clk), .D (i_in2[28]), .Q
       (o_out2[28]));
  DFFRHQX1 \o_out1_reg[30] (.RN (rst_n), .CK (clk), .D (i_in1[30]), .Q
       (o_out1[30]));
  DFFRHQX1 \o_out1_reg[28] (.RN (rst_n), .CK (clk), .D (i_in1[28]), .Q
       (o_out1[28]));
  DFFRHQX1 \o_out1_reg[24] (.RN (rst_n), .CK (clk), .D (i_in1[24]), .Q
       (o_out1[24]));
  DFFRHQX1 \o_out1_reg[16] (.RN (rst_n), .CK (clk), .D (i_in1[16]), .Q
       (o_out1[16]));
  DFFRHQX1 \o_out2_reg[3] (.RN (rst_n), .CK (clk), .D (i_in2[3]), .Q
       (o_out2[3]));
  DFFRHQX1 \o_out1_reg[0] (.RN (rst_n), .CK (clk), .D (i_in1[0]), .Q
       (o_out1[0]));
  DFFRHQX1 \o_out2_reg[0] (.RN (rst_n), .CK (clk), .D (i_in2[0]), .Q
       (o_out2[0]));
  DFFRHQX1 \o_out2_reg[31] (.RN (rst_n), .CK (clk), .D (i_in2[31]), .Q
       (o_out2[31]));
  DFFRHQX1 \o_out2_reg[5] (.RN (rst_n), .CK (clk), .D (i_in2[5]), .Q
       (o_out2[5]));
  DFFRHQX1 \o_out1_reg[15] (.RN (rst_n), .CK (clk), .D (i_in1[15]), .Q
       (o_out1[15]));
  DFFRHQX1 \o_out2_reg[30] (.RN (rst_n), .CK (clk), .D (i_in2[30]), .Q
       (o_out2[30]));
  DFFRHQX1 \o_out2_reg[29] (.RN (rst_n), .CK (clk), .D (i_in2[29]), .Q
       (o_out2[29]));
  DFFRHQX1 \o_out2_reg[8] (.RN (rst_n), .CK (clk), .D (i_in2[8]), .Q
       (o_out2[8]));
  DFFRHQX1 \o_out1_reg[23] (.RN (rst_n), .CK (clk), .D (i_in1[23]), .Q
       (o_out1[23]));
  DFFRHQX1 \o_out1_reg[14] (.RN (rst_n), .CK (clk), .D (i_in1[14]), .Q
       (o_out1[14]));
  DFFRHQX1 \o_out2_reg[26] (.RN (rst_n), .CK (clk), .D (i_in2[26]), .Q
       (o_out2[26]));
  DFFRHQX1 \o_out2_reg[27] (.RN (rst_n), .CK (clk), .D (i_in2[27]), .Q
       (o_out2[27]));
  DFFRHQX1 \o_out1_reg[13] (.RN (rst_n), .CK (clk), .D (i_in1[13]), .Q
       (o_out1[13]));
  DFFRHQX1 \o_out1_reg[31] (.RN (rst_n), .CK (clk), .D (i_in1[31]), .Q
       (o_out1[31]));
  DFFRHQX1 \o_out2_reg[25] (.RN (rst_n), .CK (clk), .D (i_in2[25]), .Q
       (o_out2[25]));
  DFFRHQX1 \o_out2_reg[12] (.RN (rst_n), .CK (clk), .D (i_in2[12]), .Q
       (o_out2[12]));
  DFFRHQX1 \o_out1_reg[27] (.RN (rst_n), .CK (clk), .D (i_in1[27]), .Q
       (o_out1[27]));
  DFFRHQX1 \o_out1_reg[22] (.RN (rst_n), .CK (clk), .D (i_in1[22]), .Q
       (o_out1[22]));
  DFFRHQX1 \o_out1_reg[12] (.RN (rst_n), .CK (clk), .D (i_in1[12]), .Q
       (o_out1[12]));
  DFFRHQX1 \o_out2_reg[14] (.RN (rst_n), .CK (clk), .D (i_in2[14]), .Q
       (o_out2[14]));
  DFFRHQX1 \o_out2_reg[24] (.RN (rst_n), .CK (clk), .D (i_in2[24]), .Q
       (o_out2[24]));
  DFFRHQX1 \o_out2_reg[23] (.RN (rst_n), .CK (clk), .D (i_in2[23]), .Q
       (o_out2[23]));
  DFFRHQX1 \o_out1_reg[11] (.RN (rst_n), .CK (clk), .D (i_in1[11]), .Q
       (o_out1[11]));
  DFFRHQX1 \o_out1_reg[8] (.RN (rst_n), .CK (clk), .D (i_in1[8]), .Q
       (o_out1[8]));
  DFFRHQX1 \o_out2_reg[22] (.RN (rst_n), .CK (clk), .D (i_in2[22]), .Q
       (o_out2[22]));
  DFFRHQX1 \o_out2_reg[21] (.RN (rst_n), .CK (clk), .D (i_in2[21]), .Q
       (o_out2[21]));
  DFFRHQX1 \o_out2_reg[11] (.RN (rst_n), .CK (clk), .D (i_in2[11]), .Q
       (o_out2[11]));
  DFFRHQX1 \o_out1_reg[10] (.RN (rst_n), .CK (clk), .D (i_in1[10]), .Q
       (o_out1[10]));
  DFFRHQX1 \o_out2_reg[20] (.RN (rst_n), .CK (clk), .D (i_in2[20]), .Q
       (o_out2[20]));
  DFFRHQX1 \o_out2_reg[19] (.RN (rst_n), .CK (clk), .D (i_in2[19]), .Q
       (o_out2[19]));
  DFFRHQX1 \o_out1_reg[9] (.RN (rst_n), .CK (clk), .D (i_in1[9]), .Q
       (o_out1[9]));
  DFFRHQX1 \o_out2_reg[18] (.RN (rst_n), .CK (clk), .D (i_in2[18]), .Q
       (o_out2[18]));
  DFFRHQX1 \o_out2_reg[9] (.RN (rst_n), .CK (clk), .D (i_in2[9]), .Q
       (o_out2[9]));
  DFFRHQX1 \o_out1_reg[29] (.RN (rst_n), .CK (clk), .D (i_in1[29]), .Q
       (o_out1[29]));
  DFFRHQX1 \o_out1_reg[26] (.RN (rst_n), .CK (clk), .D (i_in1[26]), .Q
       (o_out1[26]));
  DFFRHQX1 \o_out1_reg[20] (.RN (rst_n), .CK (clk), .D (i_in1[20]), .Q
       (o_out1[20]));
  DFFRHQX1 \o_out2_reg[16] (.RN (rst_n), .CK (clk), .D (i_in2[16]), .Q
       (o_out2[16]));
  DFFRHQX1 \o_out2_reg[15] (.RN (rst_n), .CK (clk), .D (i_in2[15]), .Q
       (o_out2[15]));
  DFFRHQX1 \o_out1_reg[7] (.RN (rst_n), .CK (clk), .D (i_in1[7]), .Q
       (o_out1[7]));
  DFFRHQX1 \o_out2_reg[13] (.RN (rst_n), .CK (clk), .D (i_in2[13]), .Q
       (o_out2[13]));
  DFFRHQX1 \o_out1_reg[19] (.RN (rst_n), .CK (clk), .D (i_in1[19]), .Q
       (o_out1[19]));
  DFFRHQX1 \o_out1_reg[6] (.RN (rst_n), .CK (clk), .D (i_in1[6]), .Q
       (o_out1[6]));
  DFFRHQX1 \o_out1_reg[21] (.RN (rst_n), .CK (clk), .D (i_in1[21]), .Q
       (o_out1[21]));
  DFFRHQX1 \o_out1_reg[5] (.RN (rst_n), .CK (clk), .D (i_in1[5]), .Q
       (o_out1[5]));
  DFFRHQX1 \o_out2_reg[10] (.RN (rst_n), .CK (clk), .D (i_in2[10]), .Q
       (o_out2[10]));
  DFFRHQX1 \o_out2_reg[17] (.RN (rst_n), .CK (clk), .D (i_in2[17]), .Q
       (o_out2[17]));
  DFFRHQX1 \o_out1_reg[25] (.RN (rst_n), .CK (clk), .D (i_in1[25]), .Q
       (o_out1[25]));
  DFFRHQX1 \o_out1_reg[18] (.RN (rst_n), .CK (clk), .D (i_in1[18]), .Q
       (o_out1[18]));
  DFFRHQX1 \o_out1_reg[4] (.RN (rst_n), .CK (clk), .D (i_in1[4]), .Q
       (o_out1[4]));
  DFFRHQX1 \o_out2_reg[7] (.RN (rst_n), .CK (clk), .D (i_in2[7]), .Q
       (o_out2[7]));
  DFFRHQX1 \o_out1_reg[3] (.RN (rst_n), .CK (clk), .D (i_in1[3]), .Q
       (o_out1[3]));
  DFFRHQX1 \o_out2_reg[6] (.RN (rst_n), .CK (clk), .D (i_in2[6]), .Q
       (o_out2[6]));
  DFFRHQX1 \o_out1_reg[17] (.RN (rst_n), .CK (clk), .D (i_in1[17]), .Q
       (o_out1[17]));
  DFFRHQX1 \o_out1_reg[2] (.RN (rst_n), .CK (clk), .D (i_in1[2]), .Q
       (o_out1[2]));
  DFFRHQX1 \o_out2_reg[4] (.RN (rst_n), .CK (clk), .D (i_in2[4]), .Q
       (o_out2[4]));
  DFFRHQX1 \o_out1_reg[1] (.RN (rst_n), .CK (clk), .D (i_in1[1]), .Q
       (o_out1[1]));
  DFFRHQX1 \o_out2_reg[2] (.RN (rst_n), .CK (clk), .D (i_in2[2]), .Q
       (o_out2[2]));
  DFFRHQX1 \o_out2_reg[1] (.RN (rst_n), .CK (clk), .D (i_in2[1]), .Q
       (o_out2[1]));
endmodule

