
// Generated by Cadence Genus(TM) Synthesis Solution 22.17-s071_1
// Generated on: Jul  8 2026 06:09:34 KST (Jul  7 2026 21:09:34 UTC)

// Verification Directory fv/mux 

module mux(i_tx0, i_rx0, i_pwm1, i_other_signal, i_select, o_data_out);
  input i_tx0, i_rx0, i_pwm1, i_other_signal;
  input [1:0] i_select;
  output o_data_out;
  wire i_tx0, i_rx0, i_pwm1, i_other_signal;
  wire [1:0] i_select;
  wire o_data_out;
  MX4XL g90__2398(.A (i_tx0), .B (i_pwm1), .C (i_rx0), .D
       (i_other_signal), .S0 (i_select[1]), .S1 (i_select[0]), .Y
       (o_data_out));
endmodule

