
// Generated by Cadence Genus(TM) Synthesis Solution 22.17-s071_1
// Generated on: Jul  8 2026 06:37:27 KST (Jul  7 2026 21:37:27 UTC)

// Verification Directory fv/FSM3 

module FSM3(clk, rst_n, go, ws, rd, ds);
  input clk, rst_n, go, ws;
  output rd, ds;
  wire clk, rst_n, go, ws;
  wire rd, ds;
  wire [1:0] state;
  wire n_0, n_1, n_2, n_3, n_4, n_5, n_6, n_7;
  DFFRHQX1 rd_reg(.RN (rst_n), .CK (clk), .D (n_7), .Q (rd));
  NAND2BX1 g222__2398(.AN (rd), .B (n_5), .Y (n_7));
  DFFRHQX1 ds_reg(.RN (rst_n), .CK (clk), .D (n_4), .Q (ds));
  INVX1 g225(.A (n_5), .Y (n_6));
  NAND2BXL g226__5107(.AN (ds), .B (n_3), .Y (n_4));
  AOI21X1 g227__6260(.A0 (ws), .A1 (state[0]), .B0 (n_2), .Y (n_5));
  DFFRHQX1 \state_reg[1] (.RN (rst_n), .CK (clk), .D (n_1), .Q
       (state[1]));
  NAND3BXL g230__4319(.AN (ws), .B (state[0]), .C (state[1]), .Y (n_3));
  AOI2BB1X1 g228__8428(.A0N (go), .A1N (state[0]), .B0 (state[1]), .Y
       (n_2));
  AOI21X1 g229__5526(.A0 (ws), .A1 (state[1]), .B0 (n_0), .Y (n_1));
  DFFRX1 \state_reg[0] (.RN (rst_n), .CK (clk), .D (n_6), .Q
       (state[0]), .QN (n_0));
endmodule

