
// Generated by Cadence Genus(TM) Synthesis Solution 22.17-s071_1
// Generated on: Jul  8 2026 06:50:06 KST (Jul  7 2026 21:50:06 UTC)

// Verification Directory fv/FSM4 

module FSM4(clk, rst_n, din_bit, dout_bit);
  input clk, rst_n, din_bit;
  output dout_bit;
  wire clk, rst_n, din_bit;
  wire dout_bit;
  wire [2:0] state;
  wire n_0, n_1, n_2, n_3, n_4, n_5, n_6, n_7;
  wire n_8, n_10, n_11, n_12, n_13;
  OAI22XL g531__2398(.A0 (state[2]), .A1 (n_11), .B0 (n_6), .B1 (n_8),
       .Y (n_13));
  DFFRHQX1 \state_reg[2] (.RN (rst_n), .CK (clk), .D (n_7), .Q
       (state[2]));
  OAI32X1 g533__5107(.A0 (din_bit), .A1 (n_10), .A2 (n_5), .B0
       (state[2]), .B1 (n_4), .Y (n_12));
  AOI211XL g536__6260(.A0 (state[0]), .A1 (n_10), .B0 (din_bit), .C0
       (n_3), .Y (n_11));
  NOR2XL g534__4319(.A (n_8), .B (n_2), .Y (dout_bit));
  NOR3X1 g535__8428(.A (n_6), .B (n_10), .C (n_5), .Y (n_7));
  AOI22X1 g538__5526(.A0 (din_bit), .A1 (n_0), .B0 (n_10), .B1 (n_1),
       .Y (n_4));
  INVXL g537(.A (n_8), .Y (n_3));
  XNOR2X1 g539__6783(.A (n_6), .B (state[2]), .Y (n_2));
  XNOR2X1 g540__3680(.A (state[2]), .B (state[0]), .Y (n_5));
  NAND2X1 g542__1617(.A (state[1]), .B (n_1), .Y (n_8));
  NAND2XL g541__2802(.A (state[1]), .B (state[0]), .Y (n_0));
  INVXL g544(.A (din_bit), .Y (n_6));
  DFFRX1 \state_reg[0] (.RN (rst_n), .CK (clk), .D (n_12), .Q
       (state[0]), .QN (n_1));
  DFFRX1 \state_reg[1] (.RN (rst_n), .CK (clk), .D (n_13), .Q
       (state[1]), .QN (n_10));
endmodule

